/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BackupsList: typeof import('./src/components/BackupsList.vue')['default']
    CoreConfiguration: typeof import('./src/components/CoreConfiguration.vue')['default']
    CreatorConfig: typeof import('./src/components/CreatorConfig.vue')['default']
    EssentialLink: typeof import('./src/components/EssentialLink.vue')['default']
    ListConfiguration: typeof import('./src/components/ListConfiguration.vue')['default']
    NotificationBox: typeof import('./src/components/NotificationBox.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ServerSetting: typeof import('./src/components/ServerSetting.vue')['default']
    SkeletonCard: typeof import('./src/components/SkeletonCard.vue')['default']
    StockageConfiguration: typeof import('./src/components/StockageConfiguration.vue')['default']
  }
}
